---
# Git Repository Settings
git:
  url: "https://github.com/vinnie-kaboom/ansible-repo"
  branch: "main"
  poll_interval: 300
  auth:
    type: "token"
    username: "vinnie-kaboom"
    token: "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"
ansible:
  playbook_dir: "playbooks"
  inventory_file: "inventory"
